# Generated by Django 5.1.2 on 2024-10-25 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='quiz_4_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='quiz_5_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='quiz_6_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
