# Generated by Django 5.1.2 on 2024-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team_log_team_quiz_4_status_team_quiz_5_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
