# Generated by Django 5.1.2 on 2024-10-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_team_end_time_team_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='time',
        ),
    ]
