# Generated by Django 5.1.2 on 2024-10-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_team_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='log',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
